fisio-web/src/main/java/com/fisio/web/bean/acao/AcaoBean.java
package com.fisio.web.bean.acao;

import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.fisio.facade.acao.AcaoFacade;
import com.fisio.framework.consulta.restricao.Restricoes;
import com.fisio.framework.facade.Facade;
import com.fisio.framework.util.VerificadorUtil;
import com.fisio.model.autenticacao.Acao;
import com.fisio.web.consulta.acao.AcaoConsulta;
import com.fisio.web.generico.AbstractBean;

@Component
@ManagedBean
@Scope("view")
public class AcaoBean extends AbstractBean<Acao>{

	private AcaoFacade acaoFacade;
	private AcaoConsulta consulta;
	
	@Autowired
	public AcaoBean(AcaoFacade acaoFacade, AcaoConsulta consulta) {
		this.acaoFacade = acaoFacade;
		this.consulta = consulta;
	}
	
	public void fecharDetalhe() {
		setDetalharVisivel(false);
		limparEntidade();
	}
		
	@Override
	protected void limparEntidade() {
		setEntidade(new Acao());
	}
	
	@Override
	public void filtro() {
		Acao acaoConsulta = new Acao();
		List<Restricoes> listaRestricoes = new ArrayList<Restricoes>();
		if(this.filtro != null){
			listaRestricoes.add(Restricoes.like("descricao", this.filtro));
		}
		setListFiltrado(this.acaoFacade.filtro(listaRestricoes, acaoConsulta, null));
	}
	
	@Override
	public Acao getEntidade() {
		if(VerificadorUtil.estaNulo(entidade)) {
			entidade = new Acao();
		}
		return entidade;
	}
	
	@Override
	protected Facade<Acao> getFacade() {
		return this.acaoFacade;
	}
	
	public AcaoConsulta getConsulta() {
		return consulta;
	}
}

fisio-web/src/main/java/com/fisio/web/bean/contasPagar/ContasPagarBean.java
package com.fisio.web.bean.contasPagar;

import static com.fisio.web.constantes.ConstantesUtilWeb.REGISTRO_CADASTRADO_COM_SUCESSO;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

import javax.faces.bean.ManagedBean;

import org.primefaces.component.datatable.DataTable;
import org.primefaces.event.CellEditEvent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.fisio.facade.categoria.CategoriaFacade;
import com.fisio.facade.contasPagar.ContasPagarFacade;
import com.fisio.framework.consulta.restricao.Restricoes;
import com.fisio.framework.contasPagar.ContasPagar;
import com.fisio.framework.facade.Facade;
import com.fisio.framework.tipoCategoria.Categoria;
import com.fisio.framework.util.VerificadorUtil;
import com.fisio.service.contasPagar.ContasPagarService;
import com.fisio.web.consulta.contasPagar.ContasPagarConsulta;
import com.fisio.web.converter.categoria.CategoriaConversor;
import com.fisio.web.framework.combomodel.ItemCombo;
import com.fisio.web.generico.AbstractBean;

@Component
@ManagedBean
@Scope("view")
public class ContasPagarBean extends AbstractBean<ContasPagar>{

	private ContasPagarFacade contasPagarFacade;
	private ContasPagarConsulta consulta;
	private ContasPagarService contasPagarService;
	
	private CategoriaFacade cantegoriaFacade;
	private CategoriaConversor categoriaConversor;
	
	private Date primeiraData;
	private Date segundaData;
	private List<ContasPagar> listFiltradoPago = new ArrayList<ContasPagar>();
	private boolean bloquear;
	
	@Autowired
	public ContasPagarBean(ContasPagarFacade contasPagarFacade, ContasPagarConsulta consulta, 
			ContasPagarService contasPagarService, CategoriaFacade categoriaFacade) {
		this.contasPagarFacade = contasPagarFacade;
		this.consulta = consulta;
		this.cantegoriaFacade = categoriaFacade;
		this.contasPagarService = contasPagarService;
		this.categoriaConversor = new CategoriaConversor();
		this.consulta.setEmpresa(getUsuarioLogado().getEmpresa());
		filtroContasPaga();
	}
	
	public void onCellEdit(CellEditEvent event) {
		ContasPagar entidade =(ContasPagar)((DataTable)event.getComponent()).getRowData();
		contasPagarFacade.alterar(entidade);
	}
	
	@Override
	public void cadastrar(ContasPagar entidade) {
		try {
			this.contasPagarService.verificarCamposObrigatorios(entidade);
			Integer numeroParcelas = Integer.valueOf(entidade.getParcelas() == null ? "1" : entidade.getParcelas());
			
			if (numeroParcelas != null && numeroParcelas > 1) {
				
				GregorianCalendar dataModificada = new GregorianCalendar();
				dataModificada.setTime(entidade.getVencimento());
				
				for (int i = 1; i <= numeroParcelas; i++) {
					ContasPagar contasPagar = new ContasPagar();
					dataModificada.set(Calendar.MONTH, i);
					contasPagar.setVencimento(dataModificada.getTime());
					contasPagar.setEmpresa(getUsuarioLogado().getEmpresa());
					contasPagar.setParcelas(String.valueOf(i) + "/"
							+ numeroParcelas);
					contasPagar.setContaFixa(false);
					contasPagar.setDescricao(entidade.getDescricao());
					contasPagar.setPago(false);
					contasPagar.setValor(entidade.getValor());
					this.contasPagarFacade.cadastrar(contasPagar);
				}
			} else {
				entidade.setParcelas(getMensagemI18n("Mensalmente"));
				entidade.setEmpresa(getUsuarioLogado().getEmpresa());
				this.contasPagarFacade.cadastrar(entidade);
			}
			atualizarDataTable();
			limparEntidade();
			setCadastrarVisivel(false);
			lancarSucesso(REGISTRO_CADASTRADO_COM_SUCESSO);
			
		} catch (Exception e) {
			lancarErro(e.getMessage());
		}
	}
	
	public void setSelecionarPaga(ContasPagar entidade) {
		if(entidade.isContaFixa()){
			ContasPagar contasPagar = new ContasPagar();
			contasPagar.setPago(true);
			contasPagar.setContaFixa(true);
			contasPagar.setValor(entidade.getValor());
			contasPagar.setVencimento(new Date());
			contasPagar.setParcelas(getMensagemI18n("Mensalmente"));
			contasPagar.setDescricao(entidade.getDescricao());
			contasPagar.setEmpresa(entidade.getEmpresa());
			contasPagar.setUsuario(getUsuarioLogado());
			contasPagar.setCategoria(getEntidade().getCategoria());
			this.contasPagarFacade.cadastrar(contasPagar);
		}else{
			entidade.setPago(true);
			entidade.setUsuario(getUsuarioLogado());
			this.contasPagarFacade.alterar(entidade);
		}
		atualizarDataTable();
	}
	
	public List<ItemCombo> getListaCategoria() {
		List<ItemCombo> listaItemCombo = new ArrayList<ItemCombo>();
		Categoria categoriaConsulta = new Categoria();
		List<Restricoes> listaRestricoes = new ArrayList<Restricoes>();

		List<Categoria> listaCategoria = this.cantegoriaFacade.consultarTodos(categoriaConsulta, listaRestricoes, categoriaConsulta.getCampoOrderBy());
		for (Categoria categoria : listaCategoria) {
				listaItemCombo.add(new ItemCombo(categoria.getDescricao(), categoria));
		}
		return listaItemCombo;
	}

	private void atualizarDataTable() {
		filtroContasPaga();
		filtro();
	}
	
	public void excluirContasPaga(ContasPagar entidade) {
		if (entidade.isContaFixa()) {
			this.contasPagarFacade.excluir(entidade);
		} else {
			entidade.setPago(false);
			this.contasPagarFacade.excluirContasParceladas(entidade);
		}
		atualizarDataTable();
	}
	
	public void fecharDetalhe() {
		setDetalharVisivel(false);
		limparEntidade();
	}
		
	@Override
	protected void limparEntidade() {
		setEntidade(new ContasPagar());
	}
	
	@Override
	public void novo() {
		desbloquear();
		super.novo();
	}
	
	@Override
	public void filtro() {
		ContasPagar contasPagarConsulta = new ContasPagar();
		List<Restricoes> listaRestricoes = new ArrayList<Restricoes>();
		listaRestricoes.add(Restricoes.igual("empresa.id", getUsuarioLogado().getEmpresa().getId()));
		listaRestricoes.add(Restricoes.igual("pago", false));
		if(this.filtro != null){
			listaRestricoes.add(Restricoes.like("descricao", this.filtro));
		}
		setListFiltrado(this.contasPagarFacade.filtro(listaRestricoes, contasPagarConsulta, null));
		
		/*if(this.filtro != null && !this.filtro.equals("__/__/____")){ */
		/*}*/
	}
	
	public void filtroContasPaga(){
		List<Restricoes> listaRestricoes = new ArrayList<Restricoes>();
		listaRestricoes.add(Restricoes.igual("empresa.id", getUsuarioLogado().getEmpresa().getId()));
		listaRestricoes.add(Restricoes.igual("pago", true));
		if(this.primeiraData != null && this.segundaData != null){
			listaRestricoes.add(Restricoes.between("vencimento", this.primeiraData, this.segundaData));
		}
		setListFiltradoPago(this.contasPagarFacade.filtro(listaRestricoes, new ContasPagar(), null));
	}
	
	public BigDecimal getValorTotal() {
		BigDecimal total = BigDecimal.ZERO;

		for (ContasPagar valor : getListFiltradoPago()) {
			total = total.add(valor.getValor());
		}
		return total;
	}
	
	public void bloquear() {
		setBloquear(entidade.isContaFixa() ? true : false);
	}
	
	public void desbloquear(){
		setBloquear(false);
	}
	
	@Override
	public ContasPagar getEntidade() {
		if(VerificadorUtil.estaNulo(entidade)) {
			entidade = new ContasPagar();
		}
		return entidade;
	}
	
	@Override
	protected Facade<ContasPagar> getFacade() {
		return this.contasPagarFacade;
	}
	
	public ContasPagarConsulta getConsulta() {
		return consulta;
	}
	
	public Date getPrimeiraData() {
		return primeiraData;
	}

	public void setPrimeiraData(Date primeiraData) {
		this.primeiraData = primeiraData;
	}

	public Date getSegundaData() {
		return segundaData;
	}

	public void setSegundaData(Date segundaData) {
		this.segundaData = segundaData;
	}

	public List<ContasPagar> getListFiltradoPago() {
		return listFiltradoPago;
	}
	
	public void setListFiltradoPago(List<ContasPagar> listFiltradoPago) {
		this.listFiltradoPago = listFiltradoPago;
	}
	
	public boolean isBloquear() {
		return bloquear;
	}
	
	public void setBloquear(boolean bloquearParcelas) {
		this.bloquear = bloquearParcelas;
	}
	
	public CategoriaConversor getCategoriaConversor() {
		return categoriaConversor;
	}
}

fisio-web/src/main/java/com/fisio/web/bean/fluxoBancario/FluxoBancarioBean.java
package com.fisio.web.bean.fluxoBancario;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.model.SelectItem;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import com.fisio.facade.banco.BancoFacade;
import com.fisio.facade.fluxoBancario.FluxoBancarioFacade;
import com.fisio.framework.banco.Banco;
import com.fisio.framework.caixa.TipoLancamento;
import com.fisio.framework.consulta.restricao.Restricoes;
import com.fisio.framework.facade.Facade;
import com.fisio.framework.fluxoBancario.FluxoBancario;
import com.fisio.framework.util.VerificadorUtil;
import com.fisio.web.consulta.fluxoBancario.FluxoBancarioConsulta;
import com.fisio.web.converter.bancoConversor.BancoConversor;
import com.fisio.web.framework.combomodel.ItemCombo;
import com.fisio.web.generico.AbstractBean;

@Component
@ManagedBean
@Scope("view")
public class FluxoBancarioBean extends AbstractBean<FluxoBancario>{

	private FluxoBancarioFacade fluxoBancarioFacade;
	private FluxoBancarioConsulta consulta;
	private BancoFacade bancoFacade;
	private BancoConversor bancoConversor;
	private Date primeiraData;
	private Date segundaData;
	private boolean pesquisarVisivel;
	private boolean totalVisivel;
	
	@Autowired
	public FluxoBancarioBean(FluxoBancarioFacade fluxoBancarioFacade, FluxoBancarioConsulta consulta,
			BancoFacade bancoFacade) {
		this.fluxoBancarioFacade = fluxoBancarioFacade;
		this.consulta = consulta;
		this.bancoFacade = bancoFacade;
		this.bancoConversor = new BancoConversor();
		this.consulta.setUsuario(getUsuarioLogado());
		this.consulta.setEmpresa(getUsuarioLogado().getPessoa().getEmpresa());
	}
	
	public void abrirPesquisa(){
		setPesquisarVisivel(true);
	}
	
	public void fecharPesquisa(){
		setPrimeiraData(null);
		setSegundaData(null);
		setPesquisarVisivel(false);
	}
	
	public void fecharDetalhe() {
		setDetalharVisivel(false);
		limparEntidade();
	}
		
	@Override
	protected void limparEntidade() {
		setEntidade(new FluxoBancario());
	}
	
	@Override
	protected void modificarEntidadeAntesDeCadastrarEhOuAlterar(FluxoBancario entidade) {
		
		entidade.setUsuario(getUsuarioLogado());
		List<Restricoes> listaRestricoes = new ArrayList<Restricoes>();
		listaRestricoes.add(Restricoes.igual("empresa.id", getUsuarioLogado().getEmpresa().getId()));
		if(VerificadorUtil.naoEstaNulo(entidade.getBanco())){
			listaRestricoes.add(Restricoes.igual("id", entidade.getBanco().getId()));
		}
		List<Banco> listaBancos = this.bancoFacade.consultarTodos(new Banco(), listaRestricoes, null);
		if(VerificadorUtil.naoEstaNulo(entidade.getTipoLancamento())){
			if(entidade.getTipoLancamento().equals(TipoLancamento.Receita)){
				for (Banco banco : listaBancos) {
					banco.setSaldo(banco.getSaldo().add(entidade.getValor()));
					this.bancoFacade.alterar(banco);
				}
			}else{
				for (Banco banco : listaBancos) {
					banco.setSaldo(banco.getSaldo().subtract(entidade.getValor()));
					this.bancoFacade.alterar(banco);
				}
			}
		}
	}
	
	@Override
	public void excluir(FluxoBancario entidade) {
		List<Restricoes> listaRestricoes = new ArrayList<Restricoes>();
		listaRestricoes.add(Restricoes.igual("empresa.id", getUsuarioLogado().getEmpresa().getId()));
		listaRestricoes.add(Restricoes.igual("id", entidade.getBanco().getId()));
		List<Banco> listaBancos = this.bancoFacade.consultarTodos(new Banco(), listaRestricoes, null);
		
		if(entidade.getTipoLancamento().equals(TipoLancamento.Receita)){
			for (Banco banco : listaBancos) {
				 banco.setSaldo(banco.getSaldo().subtract(entidade.getValor()));
				 this.bancoFacade.alterar(banco);
			}
		}else{
			for (Banco banco : listaBancos) {
				 banco.setSaldo(banco.getSaldo().add(entidade.getValor()));
				 this.bancoFacade.alterar(banco);
			}
		}
		super.excluir(entidade);
	}
	
	@Override
	public void filtro() {
		List<Restricoes> listaRestricoes = new ArrayList<Restricoes>();
		listaRestricoes.add(Restricoes.igual("empresa.id", getUsuarioLogado().getEmpresa().getId()));
		if(this.primeiraData != null && this.segundaData != null){
			listaRestricoes.add(Restricoes.between("dataLancamento", this.primeiraData, this.segundaData));
		}if(VerificadorUtil.naoEstaNulo(getEntidade().getBanco())){
			listaRestricoes.add(Restricoes.igual("banco.id", getEntidade().getBanco().getId()));
			setTotalVisivel(true);
		}
		
		fecharPesquisa();
		setListFiltrado(this.fluxoBancarioFacade.filtro(listaRestricoes, new FluxoBancario(), null));
	}
	
	public BigDecimal getValorTotal() {
		BigDecimal totalReceitas = BigDecimal.ZERO;
		BigDecimal totalDespesas = BigDecimal.ZERO;

		for (FluxoBancario valor : getListFiltrado()) {
			if (TipoLancamento.Receita.equals(valor.getTipoLancamento())) {
				totalReceitas = totalReceitas.add(valor.getValor());
			} else if (TipoLancamento.Despesa.equals(valor.getTipoLancamento())) {
				totalDespesas = totalDespesas.add(valor.getValor());
			}
		}
		
		getEntidade().setBanco(null);
		this.primeiraData = null;
		this.segundaData = null;
		return totalReceitas.subtract(totalDespesas);
	}
	
	public List<ItemCombo> getListaBanco() {
		List<ItemCombo> listaItemCombo = new ArrayList<ItemCombo>();
		Banco bancoConsulta = new Banco();
		List<Restricoes> listaRestricoes = new ArrayList<Restricoes>();
		listaRestricoes.add(Restricoes.igual("empresa.id", getUsuarioLogado().getEmpresa().getId()));
		if (VerificadorUtil.naoEstaNulo(getEntidade().getBanco())) {
			listaRestricoes.add(Restricoes.igual("id", getEntidade().getBanco().getId()));
		}
		List<Banco> listaBancos = this.bancoFacade.consultarTodos(bancoConsulta, listaRestricoes, bancoConsulta.getCampoOrderBy());
		for (Banco banco : listaBancos) {
				listaItemCombo.add(new ItemCombo(banco.getDescricao(), banco));
		}
		return listaItemCombo;
	}
	
	public SelectItem[] getTipoLancamentoValues() {
		int i = 0;
		SelectItem[] items = new SelectItem[TipoLancamento.values().length];
		for(TipoLancamento tipoLancamento : TipoLancamento.values()) {
			items[i++] = new SelectItem(tipoLancamento, tipoLancamento.getValue());
		}
		
		return items;
	}
	
	@Override
	public FluxoBancario getEntidade() {
		if(VerificadorUtil.estaNulo(entidade)) {
			entidade = new FluxoBancario();
		}
		return entidade;
	}
	
	@Override
	protected Facade<FluxoBancario> getFacade() {
		return this.fluxoBancarioFacade;
	}
	
	public FluxoBancarioConsulta getConsulta() {
		return consulta;
	}
	
	public BancoConversor getBancoConversor() {
		return bancoConversor;
	}
	
	public void setBancoConversor(BancoConversor bancoConversor) {
		this.bancoConversor = bancoConversor;
	}

	public Date getPrimeiraData() {
		return primeiraData;
	}

	public void setPrimeiraData(Date primeiraData) {
		this.primeiraData = primeiraData;
	}

	public Date getSegundaData() {
		return segundaData;
	}

	public void setSegundaData(Date segundaData) {
		this.segundaData = segundaData;
	}

	public boolean isPesquisarVisivel() {
		return pesquisarVisivel;
	}

	public void setPesquisarVisivel(boolean pesquisarVisivel) {
		this.pesquisarVisivel = pesquisarVisivel;
	}
	
	public boolean isTotalVisivel() {
		return totalVisivel;
	}
	
	public void setTotalVisivel(boolean totalVisivel) {
		this.totalVisivel = totalVisivel;
	}
}

fisio-web/src/main/webapp/paginas/fluxoCaixaRelatorio.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ps="http://primefaces.org/spark"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:a="http://xmlns.jcp.org/jsf/passthrough"
	template="/paginas/template/template.xhtml">

	<ui:param name="bean" value="#{fluxoCaixaRelatorio}" />

		<div id="tituloPagina">
			<div class="layout-portlets-box">
				<p:outputLabel value="#{msg['Relatorio']} / #{msg['Fluxo_de_Caixa']}" />
			</div>
			<br />
		</div>
		
	<ui:define name="content">
		<h:panelGroup id="panelGroupPersistir">
			<p:fieldset id="fieldSetEntidadePersistir"
				styleClass="layout-portlets-box" legend="#{msg['Relatorio']}"
				toggleable="true" toggleSpeed="500" collapsed="false"
				widgetVar="fieldsetPersistir"
				rendered="#{usuarioBean.possuiPermissao('ROLE_FLUXO_DE_CAIXA_RELATORIO_CONSULTAR')}">
					<h:form id="formularioEntidadePersistir" prependId="false" target="_blank"
						enctype="multipart/form-data">
						<div
							class="EmptyBox100{ display:block; width:100%; overflow:hidden;}">
							<p:panelGrid id="panelGridGeradorCamposPersistir" columns="2"
								cellpadding="0" cellspacing="10" layout="grid">
								
								<h:outputLabel value="#{msg['Tipo_de_Lancamento']}: " />
								<p:selectOneMenu value="#{bean.entidade.tipoLancamento}"
									effect="fade" style="width: 9em;">
									<f:selectItems value="#{bean.tipoLancamentoValues}" />
								</p:selectOneMenu> 
								
								<h:outputLabel value="#{msg['Paciente']}: " for="nome"/>
								<p:autoComplete id="nome" 
									value="#{bean.entidade.pessoa}"
									var="pessoa"
									itemLabel="#{pessoa.nome}"
									itemValue="#{pessoa}" 
									completeMethod="#{bean.completeText}" 
									converter="#{pessoaConverter}" />

								<h:outputLabel value="#{msg['Numero_do_recibo']}: " />
								<p:inputText value="#{bean.entidade.numeroRecibo}" />
								
								<h:outputLabel value="#{msg['Forma_de_Pagamento']}: " />
								<p:selectOneMenu value="#{bean.entidade.formaPagamento}"
									effect="fade" id="FormaPagamento"
									style="width: 9em;"
									converter="#{bean.formaPagamentoConversor}"
									filterMatchMode="startsWith" filter="true">
									<f:selectItem itemLabel="#{msg['Selecione']}"
										itemValue="#{null}" />
									<f:selectItems value="#{bean.listaFormaPagamento}" var="item"
										itemLabel="#{item.labelCampo}" itemValue="#{item.objetoCampo}" />
								</p:selectOneMenu>
								
								<h:outputLabel value="#{msg['Especialidade']}:" />
								<p:selectOneMenu value="#{bean.entidade.especialidade}"
									effect="fade" id="Especialidade" style="width: 9em;"
									converter="#{bean.especialidadeConversor}"
									filterMatchMode="startsWith" filter="true">
									<f:selectItem itemLabel="#{msg['Selecione']}"
										itemValue="#{null}" />
									<f:selectItems value="#{bean.listaEspecialidade}" var="item"
										itemLabel="#{item.labelCampo}" itemValue="#{item.objetoCampo}" />
								</p:selectOneMenu> 

								<h:outputText value="#{msg['Data']}:" />
								<p:row>
									<p:calendar id="filter" value="#{bean.primeiraData}" size="12"
										mask="99/99/9999" styleClass="TexAllRight"
										pattern="dd/MM/yyyy" locale="pt" navigator="true" />
									<h:outputText value="#{msg['Ate']}" /> 
									<p:calendar id="filterSegundo" value="#{bean.segundaData}"
										size="12" mask="99/99/9999" styleClass="TexAllRight" 
										pattern="dd/MM/yyyy" locale="pt" navigator="true" />
								</p:row>
						</p:panelGrid>
						</div>
						<div class="EmptyBox30" />
	
						<div
							class="EmptyBox100{ display:block; width:100%; overflow:hidden;}">
							<p:commandButton id="btn_fechar_persistir_cadastrar" value="#{msg['Imprimir']}"
								icon="fa fa-file-pdf-o Fs14 white" 
								action="#{bean.gerarRelatorio(bean.entidade)}" ajax="false" />
						</div>
					</h:form>
				</p:fieldset>
			<p:spacer height="20" />
		</h:panelGroup>
	</ui:define>
</ui:composition>